name: TeamChat
author: Kyubiilikesweat
version: '${project.version}'
main: kyubii.de.teamchatg.TeamChat
commands:
  Teamchat:
  Tc:
  Reloadteamchatconfig:
  Rltcconfig:
  Toggleteamchat:
  Toggletc:

